### ISSUE TITLE
exit ggs after one run of fetching feeds?

### ISSUE THREAD

**Issue by b79** [sloonz/ua#2]
Running `ggs ~/.config/ggsrc` fetches all the rss feeds defined in ggsrc, then waits and re-runs at a specified interval. Is it possible to run ggs so that it exits after one run of fetching feeds? Sometimes I like to bring up an internet connection, fetch feeds, then close down the connection. I'd like to avoid having to issue Ctrl-C to stop ggs from running.

**Comment by sloonz** [comment]
Added a -once flag : https://github.com/sloonz/ua/commit/84b48c6205ffffaf11202b18d6370edccec8264e
